services:
  backend:
    build:
      context: ./BE
    env_file:
      - ./BE/.env
    restart: unless-stopped
    ports:
      - '${BE_PORT:-9000}:${BE_PORT:-9000}'
    environment:
      - PORT=${BE_PORT:-9000}
    volumes:
      - ./BE/uploads:/app/uploads
      - ./BE/database.sqlite:/app/database.sqlite

  frontend:
    build:
      context: ./FE
    env_file:
      - ./FE/.env
    restart: unless-stopped
    ports:
      - '${FE_PORT:-3000}:${FE_PORT:-3000}'
    environment:
      - PORT=${FE_PORT:-3000}
    depends_on:
      - backend

