services:
  backend:
    build:
      context: ./BE
    env_file:
      - ./BE/.env
    restart: unless-stopped
    ports:
      - '9000:9000'
    volumes:
      - ./BE/uploads:/app/uploads
      - ./BE/database.sqlite:/app/database.sqlite

  frontend:
    build:
      context: ./FE
    env_file:
      - ./FE/.env
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - backend

