services:
  backend:
    build:
      context: ./BE
    env_file:
      - ./BE/.env
    restart: unless-stopped
    ports:
      - '9000:9000'
    environment:
      NODE_ENV: production
      PORT: 9000
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      DB_PATH: /app/database.sqlite
    volumes:
      - ./BE/uploads:/app/uploads
      - ./BE/database.sqlite:/app/database.sqlite
    depends_on:
      - frontend

  frontend:
    build:
      context: ./FE
    env_file:
      - ./FE/.env
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:9000/api}
      # Biến môi trường cho server-side API routes để kết nối đến backend service trong Docker
      BACKEND_INTERNAL_URL: http://backend:9000/api
      NEXT_PUBLIC_ENV: ${NEXT_PUBLIC_ENV:-production}
      NEXT_PUBLIC_FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}

